### ISSUE TITLE
Not Found

### ISSUE THREAD

**Issue by shuntera** [ajeetraina/nagios-centos-arm#2]
When pulling or trying to run I get the following:

Pulling repository docker.io/ajeetraina/nagios-armh
docker: Error: image ajeetraina/nagios-armh:latest not found.

**Comment by ajeetraina** [comment]
Hello Shuntera,

Thanks for trying it out. There is no image called ajeetraina/nagios-armh but the given steps are - how to build Docker image of your own using this github repository. All you possibly need to perform is:

$sudo git clone  https://github.com/ajeetraina/nagios-centos-arm
Cloning into 'nagios-centos-arm'...
remote: Counting objects: 26, done.
remote: Total 26 (delta 0), reused 0 (delta 0), pack-reused 26
Unpacking objects: 100% (26/26), done.
Checking connectivity... done.

$sudo docker build -t ajeetraina/nagios-armhh .
Sending build context to Docker daemon 94.21 kB
Step 1/9 : FROM ajeetraina/centos7-arm
latest: Pulling from ajeetraina/centos7-arm
5584ea4c92c5: Pull complete 
a3ed95caeb02: Pull complete 
Digest: sha256:10989b1b7a3bdf826857ba5b3348956d495b9be1ced644a3aa7321cfbd705b04
Status: Downloaded newer image for ajeetraina/centos7-arm:latest
 ---> 495db0a341d8
Step 2/9 : MAINTAINER "Ajeet S Raina" <Ajeet_Raina@dell.com>
 ---> Running in 7d61b1e1622b
 ---> 6db016afd749
Removing intermediate container 7d61b1e1622b
Step 3/9 : ADD nrpe /etc/init.d/
 ---> 0b6351933a9a
Removing intermediate container e20bd42756ad
Step 4/9 : RUN chmod +x /etc/init.d/nrpe
 ---> Running in dd95bb9b042a
......

This should be performed on ARM-based devices.

**Comment by Ekus** [comment]
On my virgin HypriotOS raspberry pi I was getting this error:

> unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/pirate/Dockerfile: no such file or directory

I then added this command which helped (I had already cloned the git repo although I had to set up proxy on my pi due to corporate intranet)

`  cd nagios-centos-arm/ `

 I'm newbie in linux and esp. docker so it may be obvious but it was not mentioned in the 2-step process on the main page (readme.md)

**Comment by shuntera** [comment]
The version of Nagios is as follows:
Nagios® Core™
Version 4.0.8
August 12, 2014

Any way to update that.  I assume the updater on the mail screen would not try and download a Raspberry Pi compatible version.
